name: Cypress_LambdaTest Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:[ feature/LambdaTest_Integration_with_Cypress ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - name: CheckOut
        uses: actions/checkout@v2

    # Runs a single command using the runners shell

      - name: Cupress run
        uses: cypress-io/githubaction@v2
        with:
          build: npm run build
          start: npm start
          run: lambdatest-cypress run
          working-directory: ./Cypress_LambdaTest

    # Runs a single command using the runners shell    
