name: Cypress_LambdaTest Build
on: 
  push:
    branches:
      - feature/lembda-test
    paths:
      - 'Cypress_LambdaTest/**'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
# Steps represent a sequence of tasks that will be executed as part of the job
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: NPM with Cypress
      run : npm config set legacy-peer-deps true
    - name: NPM install
      run: |-
        cd Cypress_LambdaTest
        npm install
    - name: Install LambdaCLI
      run: npm install -g lambdatest-cypress-cli  
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        command: lambdatest-cypress run
        record: true
        working-directory: Cypress_LambdaTest
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
