name: Cypress_LambdaTest Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
# Steps represent a sequence of tasks that will be executed as part of the job
     - name: CheckOut
       uses: actions/checkout@v2
       
     - name: Cupress run
       uses: cypress-io/github-action@v4
       with:
           install: | 
            npm config set legacy-peer-deps true
            npm install
           build: npm run build
           start: npm start
           working-directory: ./Cypress_LambdaTest
           command: lambdatest-cypress run
           spec: |
              QA-Tools/Cypress_LambdaTest/
              cypress/e2e/e2e testing/Common/*.cy.js
           record: true
       env:
              CYPRESS_RECORD_KEY: ${{ secrets.f6e78c45-1c38-45b2-b600-a9e54eb54c34 }}
              GITHUB_TOKEN: ${{ secrets.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 }}
       

 


    
         
