name: Cypress_LambdaTest Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
# Steps represent a sequence of tasks that will be executed as part of the job
     - name: CheckOut
       uses: actions/checkout@v2
     - name: Cupress run
       uses: cypress-io/github-action@v4
      
       with:
           project: ./Cypress_LambdaTest
           build: npm run build
           start: npm start
           working-directory: e2e
           run: lambdatest-cypress run
           record: true
       env:
              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       

 


    
         
